#!/usr/bin/env bash
# Displays 'Best School' 10x using a while loop
# Displays 'Hi' on new line on 9th iteration

i=0

while [ $i -lt 10 ]
do
  echo "Best School"
  (( i++ ))
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
done
