#!/usr/bin/env bash
# Upon looping from 1 - 10 using while loop, displays:
# 'bad luck' on 4th iteration
# 'good luck on 8th iteration' and
# 'Best School' for other iterations

i=1

while [ $i -lt 11 ]
do
  if [ $i -eq 4 ]
  then
    echo "bad luck"
  elif [ $i -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
