#!/usr/bin/env bash
# Upon looping from 1 - 20 using while loop, displays:
# each number and then
# 'bad luck from China' on 4th iteration
# 'bad luck from Japan' 9th iteration and
# 'bad luck from Italy' on 17th iteration

i=1

while [ $i -lt 21 ]
do
  echo "$i"
  case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( i++ ))
done
